app:
  name: "Microkube"
  domain: "app.local"
  subdomain: "www"
ssl:
  enabled: true
  email: "support@example.com"
images:
  peatio: rubykube/peatio:2.0.23-alpha
  barong: rubykube/barong:2.0.39-alpha
  frontend: gcr.io/openware-production/baseapp:2.1.32
  tower: rubykube/tower:0.1.8
  postmaster: quay.io/openware/postmaster:0.0.6
  components-docs: gcr.io/openware-production/components-docs:latest
  arke: rubykube/arke:0.1.5
vendor:
  frontend: git@github.com:openware/baseapp.git
storage:
  provider: "Google"
  bucketName: "microkube-barong-docs-bucket"
  accessKey: "**********"
  secretKey: "**********"
terraform:
  credentials: "~/safe/microkube.json"
  git_key: "~/.ssh/id_rsa"
  project: "example-microkube"
  region: "europe-west4"
  zone: "europe-west4-a"
  instance_name: "microkube-cloud"
  machine_type: "n1-standard-4"
  image: "debian-cloud/debian-9"
twilio:
  phone_number: "+15005550000"
  account_sid: "changeme"
  auth_token: "changeme"
recaptcha:
  type: "none"
  siteKey: "changeme"
  secretKey: "changeme"
smtp:
  host: smtp.sendgrid.net
  port: 2525
  user: apikey
  password: changeme
  sender_email: noreply@postmaster.com
  sender_name: Postmaster
wallets:
  - kind: deposit
    address: "changeme"
    nsig: 1
    max_balance: 0.0
    secret: changeme
  - kind: hot
    address: "changeme"
    nsig: 1
    max_balance: 100.0
    secret: changeme
  - kind: warm
    address: "changeme"
    nsig: 1
    max_balance: 1000.0
    secret: changeme
arke:
  strategy:
    type: 'copy'
    pair: 'ETHUSD'
    target:
      driver: rubykube
      host: 'http://www.app.local'
      name: John
      key: changeme
      secret: changeme
    sources:
      - driver: bitfinex
        name: Joe
        key: changeme
        secret: changeme
