app:
  name: "Microkube"
  domain: "app.local"
  subdomain: "www"
ssl:
  enabled: true
  email: "support@example.com"
images:
  peatio: rubykube/peatio:2.0.20-alpha
  barong: rubykube/barong:2.0.39-alpha
  frontend: gcr.io/openware-production/baseapp:0.1.56
  tower: rubykube/tower:0.1.8
  postmaster: quay.io/openware/postmaster:0.0.3
  components-docs: gcr.io/openware-production/components-docs:latest
vendor:
  frontend: https://github.com/rubykube/mikroapp.git
storage:
  provider: "Google"
  bucketName: "microkube-barong-docs-bucket"
  accessKey: "**********"
  secretKey: "**********"
terraform:
  credentials: "~/safe/microkube.json"
  git_key: "~/.ssh/id_rsa"
  project: "example-microkube"
  region: "europe-west4"
  zone: "europe-west4-a"
  instance_name: "microkube-cloud"
  machine_type: "n1-standard-4"
  image: "debian-cloud/debian-9"
twilio:
  phone_number: "+15005550000"
  account_sid: "changeme"
  auth_token: "changeme"
recaptcha:
  type: "none"
  siteKey: "changeme"
  secretKey: "changeme"
sendgrid_api_key: changeme
