logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[api]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "local"
watch = true
exposedbydefault = false

[acme]
email = "support@heliostech.fr"
storage = "acme.json"
entryPoint = "https"
OnHostRule = true
usebindportip = true

[acme.httpChallenge]
entryPoint = "http"
