- name:             Ethereum Deposit Wallet
  blockchain_key:   eth-rinkeby
  currency_id:      eth
  address:          '0x2b9fBC10EbAeEc28a8Fc10069C0BC29E45eBEB9C'
  kind:             deposit
  nsig:             1
  max_balance:      0.0
  status:           active
  gateway:          geth
  settings:
    uri:            http://geth:8545
    secret:         'changeme'

- name:             Ethereum Hot Wallet
  blockchain_key:   eth-rinkeby
  currency_id:      eth
  address:          '0x0f493226a8a98363e9a85e6b8eca468a18cc6fbb'
  kind:             hot
  nsig:             1
  max_balance:      100.0
  status:           active
  gateway:          geth
  settings:
    uri:            http://geth:8545
    secret:         'test'

- name:             Trust Deposit Wallet
  blockchain_key:   eth-rinkeby
  currency_id:      trst
  address:          '0x2b9fBC10EbAeEc28a8Fc10069C0BC29E45eBEB9C'
  kind:             deposit
  nsig:             1
  max_balance:      0.0
  status:           active
  gateway:          geth
  settings:
    uri:            http://geth:8545
    secret:         'changeme'

- name:             Trust Hot Wallet
  blockchain_key:   eth-rinkeby
  currency_id:      trst
  address:          '0x0f493226a8a98363e9a85e6b8eca468a18cc6fbb'
  kind:             hot
  nsig:             1
  max_balance:      100.0
  status:           active
  gateway:          geth
  settings:
    uri:            http://geth:8545
    secret:         'test'
